type OpaqueColorValue = symbol & { __TYPE__: 'Color' };
type ColorValue = string | OpaqueColorValue;
type vdir = 't' | 'b'
type hdir = 'l' | 'r'
type dir = vdir | hdir
export type mpbcbwType = dir | 's' | 'e' | 'h' | 'v' | 'tl' | 'lt' | 'tr' | 'rt' | 'bl' | 'lb' | 'br' | 'rb' | 'th' | 'ht' | 'vr' | 'rv' | 'bh' | 'hb' | 'vl' | 'lv'
export type brType = dir | 'be' | 'eb' | 'bs' | 'sb' | 'bl' | 'lb' | 'br' | 'rb' | 'te' | 'et' | 'ts' | 'st' | 'tl' | 'lt' | 'tr' | 'rt' | 'tbr' | 'tbl' | 'btr' | 'btl'
export type mpSize = number | string
export type Color = ColorValue
export type borderStyleType = 's' | '.' | '-'
export type fontWeightType = 'n' | 'b' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
export type fv = 'sc' | 'on' | 'ln' | 'tn' | 'pn'
export type fontVariantType = fv[]
export type textAlignType = 'a' | "c" | 'l' | 'r' | 'j'
export type textAlignVerticalType = 'a' | "c" | 't' | 'b'
export type textDecorationStyleType = borderStyleType | 'd'
export type textDecorationLineType = 'n' | 'u' | 'l' | 'ul'
export type textTransformType = 'u' | 'l' | 'c' | 'n'
type m = 'fs' | 'fe' | 'c'
type alignM = m | 's'
type spaces = 'sb' | 'sa'
export type alignItemsType = alignM | 'b'
export type alignSelfType = alignItemsType | 'a'
export type alignContentType = alignM | spaces
export type writingDirectionType = hdir | 'a'
export type DirectionType = hdir | 'i'
export type flexDirectionType = 'r' | 'rc' | 'c' | 'cc'
export type flexWrapType = 'w' | 'nw' | 'wr'
export type justifyContentType = m | spaces | 'se'
export type overflowType = 'v' | 'h' | 's'
export type resizeModeType = 'cov' | 'con' | 's' | 'r' | 'c'